### ISSUE TITLE
I'll be back

### ISSUE THREAD

**Issue by km9173** [km9173/OOPArtsWorld#8]
업무가 많은 관계로 미루어 두었지만!!
06/25 일부터 다시 개발 시작!

**Comment by seobyeongky** [comment]
경모 짱짱맨

**Comment by km9173** [comment]
병기 도와줘.. 혼자 하기 외로움

**Comment by GameEgg** [comment]
ㅋㅋㅋ

**Comment by GameEgg** [comment]
나도 공부할겸 조금씩 건드려봐도 되겠지? ㅋㅋ

**Comment by km9173** [comment]
ㅇㅇ 부디 건들여줘

**Comment by km9173** [comment]
commit 적용해서 http://ooparts.grapescandy.com/  올림 
바로바로 적용해보고 싶으면 서버 계정 하나 파서 줄수도있음. 필요하면 말하셈ㅋㅋ

**Comment by GameEgg** [comment]
로컬서버로 하는중 ㅋㅋ

**Comment by km9173** [comment]
너가 develop에 올려놓은 뒤로가기 버튼 commit 내가 받아서 서버 재시작했단말이였음 ㅋㅋ
http://ooparts.grapescandy.com/ 가보면 뒤로가기 링크있음.

**Comment by GameEgg** [comment]
아. 브라우저 캐싱 때문에 예전게 보였나봐. '_'
